### ISSUE TITLE
Providing an IdCacheResolver and IdCacheKeyGenerator with Apollo Kotlin

### ISSUE THREAD

**Issue by sonatard** [apollographql/apollo-kotlin-normalized-cache-incubating#41]
Are you planning to provide an IdCacheResolver and IdCacheKeyGenerator?

I am using IdCacheResolver, but I find it a bit tedious to make adjustments in line with changes to the CacheResolver API without migration documentation.

I believe that IdCacheResolver is the most common cache mechanism in the GraphQL world.

**Comment by BoD** [comment]
We usually recommend to use [declarative Ids](https://www.apollographql.com/docs/kotlin/caching/declarative-ids/) with `@cachePolicy` and `@fieldPolicy`, but it is true that if all your types consistently have a key field with the same name, the programmatic way can be more convenient.

**Comment by sonatard** [comment]
That's right. It's quite cumbersome to set directives for all types, so I'm using Programmatic Ids instead of declarative Ids. In particular, since the types in the schema increase according to the server's needs, I don't want the client-side engineers to be too aware of it.
