### ISSUE TITLE
Normalized cache viewer does not work with incubating cache

### ISSUE THREAD

**Issue by jvanderwee** [apollographql/apollo-kotlin-normalized-cache-incubating#42]
We've started using the incubating cache for Relay-style pagination as described [here](https://apollographql.github.io/apollo-kotlin-normalized-cache-incubating/pagination.html#relay-style-pagination). It's working beautifully 🙌  however the normalized cache viewer in the Android Studio plugin no longer works. We see the following when attempting to pull from device:

![CleanShot 2024-09-25 at 13 57 34](https://github.com/user-attachments/assets/12e56e13-71f1-411f-a611-1c0979bccda9)

**Comment by BoD** [comment]
Thanks for reporting! I'll have a look.

**Comment by BoD** [comment]
The fix is merged and will be in the next release.
