### ISSUE TITLE
Fragment optimistic updates

### ISSUE THREAD

**Issue by Mordred** [apollographql/apollo-kotlin-normalized-cache-incubating#55]
There is existing API for writing optimistic updates `writeOptimisticUpdates`. But it is for operations. It would be nice to have ability to optimistic update fragments so that I don't have to always create whole operation if I need to update only one field in specific fragment which can be very deeply nested in the query.

**Comment by BoD** [comment]
Hi! Thanks for opening this.

I'm wondering how you would use this? For operations, optimistic updates are done like
```kotlin
apolloClient.mutation(mutation)
    .optimisticUpdates(myData)
    .execute()
```

but to write fragments, since you need to go through the `ApolloStore` API, I'm not sure how it would be used?

**Comment by Mordred** [comment]
Sorry, I will try to explain my problem.

I wrote own optimistic update interceptor, which accept closure, so that I can optimistically update multiple queries and revert them all if something goes wrong.

I have an application were users track their weigh every day. To render home screen I need at least 3 different queries: 
 - one query to fetch user with settings and basic stats -> records counts, best streak, etc. Also user has last 7 days of records.
 - another query is collecting data for graph
 - and another one is paginating over records so that user can edit each

When user wants to add weight record for current day, he has to run mutation. This mutation is returning only the created record, but I want optimistically update all queries so that user see changed data as soon as possible - also revert them if something failed. I have to update records count and best streak on user query, edit last 7 days records on user, add new record to graph data and add new record to paginated query of records.

That is 3 queries which has to be constructed using `.copy`. And they can be really deeply nested.

In this example I can update user fragment directly.

When user edit specific day record, I could update graph record fragment and paginated record fragment without creating whole operation.

**Comment by BoD** [comment]
Thanks a lot for the extensive answer, that's helpful!

So I'm assuming you're already directly using the `ApolloStore` `writeOptimisticUpdates` API in your interceptor, right?

In that case, an additional `ApolloStore` API for fragments, e.g. something like

```kotlin
  fun <D : Fragment.Data> writeOptimisticUpdates(
      fragment: Fragment<D>,
      cacheKey: CacheKey,
      fragmentData: D,
      mutationId: Uuid,
      customScalarAdapters: CustomScalarAdapters = CustomScalarAdapters.Empty,
  ): Set<String>
```

would work for you?

Then in your app code you can call `rollbackOptimisticUpdates` with the given uuid after the call is made.

**Comment by Mordred** [comment]
Yes, that is exactly improvement which will help.

My interceptor is like this (maybe it can be part of the library 😀):

```kotlin
class SuperOptimisticScope(
    private val store: ApolloStore,
    private val customScalarAdapters: CustomScalarAdapters,
) {
    val requestUuids = mutableListOf<Uuid>()
    val keysForPublishing = mutableSetOf<String>()

    /**
     * Write an optimistic update to the store.
     * You do not need to call publish, keys are published automatically at the end of the scope
     */
    fun <D : Operation.Data> writeOptimisticUpdate(operation: Operation<D>, data: D) {
        // Create new UUID for each optimistic update so that we can rollback them all later
        val id = uuid4()
        keysForPublishing += store.writeOptimisticUpdates(operation, data, id, customScalarAdapters)
        requestUuids += id
    }

    // Allow to access this API from scope
    fun <D : Fragment.Data> readFragment(
        fragment: Fragment<D>,
        cacheKey: CacheKey,
        customScalarAdapters: CustomScalarAdapters = CustomScalarAdapters.Empty,
        cacheHeaders: CacheHeaders = CacheHeaders.NONE,
    ) = store.readFragment(fragment, cacheKey, customScalarAdapters, cacheHeaders)

    // Allow to access this API from scope
    fun <D : Operation.Data> readOperation(
        operation: Operation<D>,
        customScalarAdapters: CustomScalarAdapters = CustomScalarAdapters.Empty,
        cacheHeaders: CacheHeaders = CacheHeaders.NONE,
    ) = store.readOperation(operation, customScalarAdapters, cacheHeaders)
}

internal class SuperOptimisticUpdatesContext(
    val value: suspend SuperOptimisticScope.() -> Unit
) : ExecutionContext.Element {
    override val key: ExecutionContext.Key<*>
        get() = Key

    companion object Key : ExecutionContext.Key<SuperOptimisticUpdatesContext>
}

fun <T> MutableExecutionOptions<T>.superOptimisticUpdates(value: suspend SuperOptimisticScope.() -> Unit) =
    addExecutionContext(
        SuperOptimisticUpdatesContext(value)
    )

val <D : Operation.Data> ApolloRequest<D>.superOptimisticData
    get() = executionContext[SuperOptimisticUpdatesContext]?.value

class ApolloSuperOptimisticInterceptor(private val store: ApolloStore) : ApolloInterceptor {

    override fun <D : Operation.Data> intercept(
        request: ApolloRequest<D>,
        chain: ApolloInterceptorChain
    ): Flow<ApolloResponse<D>> = flow {
        val customScalarAdapters = request.executionContext[CustomScalarAdapters]!!

        val superOptimisticData = request.superOptimisticData
        if (superOptimisticData == null) {
            emitAll(chain.proceed(request))
            return@flow
        }

        val optimisticScope = SuperOptimisticScope(store, customScalarAdapters)
        // Collect all optimistic updates
        try {
            superOptimisticData(optimisticScope)
            val keys = optimisticScope.keysForPublishing
            store.publish(keys)
        } catch (e: CacheMissException) {
            // Ignore cache miss errors
            // It means that some of the required cache data are missing
            Logger.e(tag = "ApolloSuperOptimistic", e) {
                "Cannot optimistic update"
            }
        }

        var networkException: ApolloException? = null
        val networkResponses: Flow<ApolloResponse<D>> = chain.proceed(request)
            .onEach {
                networkException = it.exception
            }

        var optimisticKeys: Set<String>? = null

        var previousResponse: ApolloResponse<D>? = null
        networkResponses.collect { response ->
            if (previousResponse != null) {
                throw DefaultApolloException("Apollo: super optimistic updates can only be applied with one network response")
            }
            previousResponse = response
            if (optimisticKeys == null) {
                // Rollback optimistic updates
                optimisticKeys = optimisticScope.rollbackOptimisticUpdates(store)
            }

            if (optimisticKeys?.isNotEmpty() == true) {
                store.publish(optimisticKeys!!)
            }
            emit(response)
        }

        if (networkException != null) {
            if (optimisticKeys == null) optimisticKeys = optimisticScope.rollbackOptimisticUpdates(store)

            store.publish(optimisticKeys!!)
        }
    }
}

// Internal so that is not visible in the scope API
private fun SuperOptimisticScope.rollbackOptimisticUpdates(store: ApolloStore): Set<String> {
    val removedKeys = mutableSetOf<String>()
    for (id in requestUuids) {
        removedKeys += store.rollbackOptimisticUpdates(id)
    }
    return removedKeys
}
```

I needed to create new UUID for each write and then rollback them all, because rollback is rollbacking only first patch with given mutation ID (https://github.com/apollographql/apollo-kotlin-normalized-cache-incubating/blob/b32aefab1e30d380aa66ccef60feb82719d5d2f4/normalized-cache-incubating/src/commonMain/kotlin/com/apollographql/cache/normalized/internal/OptimisticNormalizedCache.kt#L148)

Back to my example:
UserQuery has last 7 days records on type User and also WeighinsQuery has these same records somewhere in the list. If I want to optimistically edit one record, I have to recreate UserQuery.Data and WeighinsQuery.Data and edit given weigh-in in both. Calling `writeOptimisticUpdates` for each operation with same ID will create two patches in the journal with same `CacheKey` and `mutationId`, but rollback will remove only one. I needed to call multiple times `rollbackOptimisticUpdates` until returned keys are empty. But later I created code above and assign each write own custom ID so that they can be rollbacked more easily.

So if I can edit only the fragment it would be great.

**Comment by BoD** [comment]
Thanks a lot for the detailed reply! I've just opened #60 that adds the `ApolloStore` api. Let me know what you think!

**Comment by BoD** [comment]
This is part of [v0.0.4](https://github.com/apollographql/apollo-kotlin-normalized-cache-incubating/releases/tag/v0.0.4) that has just been released.
